/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Coupling;

import ctrlStricture.CtrlWeight;
import static home.CM_ToolHOME.jDesktopPane1;

/**
 *
 * @author User
 */
public class CouplingTbl extends javax.swing.JInternalFrame {

    /**
     * Creates new form CouplingTbl
     */
    public CouplingTbl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(699, 547));
        setMinimumSize(new java.awt.Dimension(699, 547));
        setPreferredSize(new java.awt.Dimension(699, 547));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "import java.util.Scanner;", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"2", "class Years{", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"3", "public int getYear(){", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"4", "int year;", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"5", "String enteredYear;", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"6", "Scanner sc = new Scanner(System.in);", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"7", "System.out.println(\"Enter the year as a number :\");", "0", "1", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "2"},
                {"8", "enteredYear = sc.next();", "0", "1", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "2"},
                {"9", "year = Integer.parseInt(enteredYear);", "0", "1", null, "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "2"},
                {"10", "return year;", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"11", "}", "0", "0", "0", null, "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"12", " }", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"13", "//------------------------------------------------------------------------------------------------------------------------------------", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"14", "class Months extends Years{", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"15", "public int getMonth(){", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", null, "0"},
                {"16", "int month;", "0", "0", null, "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"17", "String enteredMonthNumber;", "0", "0", "0", null, "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"18", "Scanner sc = new Scanner(System.in);", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"19", "System.out.println(\"Enter the month number :\");", "0", "1", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "2"},
                {"20", "enteredMonthNumber = sc.next();", "0", "1", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "2"},
                {"21", "month = Integer.parseInt(enteredMonthNumber);", "0", "1", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "2"},
                {"22", "return month;", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"23", " }", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"24", " }", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"25", "//------------------------------------------------------------------------------------------------------------------------------------", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"26", "class DaysPerMonth extends Months{ ", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"27", " static int numDays = 0;", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"28", " public static void main(String[] args) {", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"29", "int year;", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"30", "Months m = new Months();", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"31", " int month = m.getMonth();", "0", "1", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "2"},
                {"32", "if((month < 1) || (month > 12)){ ", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"33", " System.out.println(\"Kindly enter a number between 0 to 13.\");", "0", "1", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "2"},
                {"34", " }", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"35", "else {", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"36", "case 1:", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"37", "case 3:", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"38", "case 5:", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"39", "case 7:", "0", "0", null, "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"40", "case 8:", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"41", " case 10:", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"42", "case 12:", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"43", "numDays = 31;", "0", "0", "0", "0", "0", "0", "0", "0", "0", "1", "0", "0", "0", "1"},
                {"44", "System.out.println(\"Month \" + month + \" consists of \" + numDays + \" days.\");", "0", "1", "0", "0", "0", "0", "0", "0", "0", "1", "0", "0", "0", "3"},
                {"45", " break;", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"46", " case 4:", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"47", "case 6:", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"48", "case 9:", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"49", "case 11:", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"50", "numDays = 30;", "0", "0", "0", "0", "0", "0", "0", "0", "0", "1", "0", "0", "0", "0"},
                {"51", "System.out.println(\"Month \" + month + \" consists of \" + numDays + \" days.\");", "0", "1", "0", "0", "0", "0", "0", "0", "0", "1", "0", "0", "0", "3"},
                {"52", " break;", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"53", "case 2:", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"54", "year = m.getYear();", "0", "1", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "2"},
                {"55", "if(year < 1) {", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "00", "0", "0"},
                {"56", "System.out.println(\"Kindly enter a valid year.\");", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"57", "  }", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"58", "else{", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"59", "  if(((year % 4 == 0) &&  !(year % 100 == 0)) || (year % 400 == 0)){", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"60", " numDays = 29;", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"61", "if(year > 2020){", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"62", "  System.out.println(\"In year \" + year + \" month \" + month + \" will consist of \" + numDays + \" days.\");", "0", "1", "0", "0", "0", "0", "0", "0", "0", "1", "0", "0", "0", "3"},
                {"63", " }", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"64", "else{", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"65", "System.out.println(\"In year \" + year + \" month \" + month + \" has consisted of \" + numDays + \" days.\");", "0", "1", "0", "0", "0", "0", "0", "0", "0", "1", "0", "0", "0", "3"},
                {"66", " }", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"67", "}//if at line 61", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"68", "else{", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"69", "numDays = 28;", "0", "0", "0", "0", "0", "0", "0", "0", "0", "1", "0", "0", "0", "1"},
                {"70", "if (year > 2020){", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"71", " System.out.println(\"In year \" + year + \" month \" + month + \" will consist of \" + numDays + \" days.\");", "0", "1", "0", "0", "0", "0", "0", "0", "0", "1", "0", "0", "0", "3"},
                {"72", " }", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"73", "else{", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"74", " System.out.println(\"In year \" + year + \" month \" + month + \" has consisted of \" + numDays + \" days.\");", "0", "1", "0", "0", "0", "0", "0", "0", "0", "1", "0", "0", "0", "3"},
                {"75", " }", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"76", "break;", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"77", "}//else at line 70", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"78", "}//else at line 60", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"79", "}//switch at line 37", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"80", "}//else at line 36", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"81", "}//method", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
                {"82", "}//class", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"}
            },
            new String [] {
                "no", "Program statements", "Nr", "Nmcms", "Nmcmd", "Nmcrms", "Nmcrmd", "Nrmcrms", "Nrmcrmd", "Nrmcms", "Nrmcmd", "Nmrgvs", "Nmrgvd", "Nrmrgvs", "Nrmrgvd", "Ccp"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Change weights");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (weight == null) {
            jDesktopPane1.removeAll();
            CouplingWeight tbl = new CouplingWeight();
            jDesktopPane1.add(tbl).setVisible(true);
            this.setVisible(false);
        } else {
            jDesktopPane1.removeAll();
            jDesktopPane1.add(weight).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    CouplingWeight weight;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
