/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inheritance;

import ctrlStricture.CtrlWeight;
import static home.CM_ToolHOME.jDesktopPane1;

/**
 *
 * @author SupzPC
 */
public class InheriteShow_Page extends javax.swing.JInternalFrame {

    /**
     * Creates new form InheriteShow_Page
     */
    public InheriteShow_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Inheritance_Sum");
        setMaximumSize(new java.awt.Dimension(699, 547));
        setMinimumSize(new java.awt.Dimension(699, 547));
        setPreferredSize(new java.awt.Dimension(699, 547));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "", "", "", "", ""},
                {"2", "Years", "0", "0", "0", "0"},
                {"3", null, null, null, null, null},
                {"4", null, null, null, null, null},
                {"5", null, null, null, null, null},
                {"6", null, null, null, null, null},
                {"7", null, null, null, null, null},
                {"8", null, null, null, null, null},
                {"9", null, null, null, null, null},
                {"10", null, null, null, null, null},
                {"11", null, null, null, null, null},
                {"12", null, null, null, null, null},
                {"13", null, null, null, null, null},
                {"14", "Months", "1", "0", "1", "1"},
                {"15", null, null, null, null, null},
                {"16", null, null, null, null, null},
                {"17", null, null, null, null, null},
                {"18", null, null, null, null, null},
                {"19", null, null, null, null, null},
                {"20", null, null, null, null, null},
                {"21", null, null, null, null, null},
                {"22", null, null, null, null, null},
                {"23", null, null, null, null, null},
                {"24", null, null, null, null, null},
                {"25", "", null, null, null, null},
                {"26", "DaysPerMonth ", "1", "2", "3", "3"},
                {"27", null, null, null, null, null},
                {"28", null, null, null, null, null},
                {"29", null, null, null, null, null},
                {"30", null, null, null, null, null},
                {"31", null, null, null, null, null},
                {"32", null, null, null, null, null},
                {"33", null, null, null, null, null},
                {"34", null, null, null, null, null},
                {"35", null, null, null, null, null},
                {"36", null, null, null, null, null},
                {"37", null, null, null, null, null},
                {"38", null, null, null, null, null},
                {"39", null, null, null, null, null},
                {"40", null, null, null, null, null},
                {"41", null, null, null, null, null},
                {"42", null, null, null, null, null},
                {"43", null, null, null, null, null},
                {"44", null, null, null, null, null},
                {"45", null, null, null, null, null},
                {"46", null, null, null, null, null},
                {"47", null, null, null, null, null},
                {"48", null, null, null, null, null},
                {"49", null, null, null, null, null},
                {"50", null, null, null, null, null},
                {"51", null, null, null, null, null},
                {"52", null, null, null, null, null},
                {"53", null, null, null, null, null},
                {"54", null, null, null, null, null},
                {"55", null, null, null, null, null},
                {"56", null, null, null, null, null},
                {"57", null, null, null, null, null},
                {"58", null, null, null, null, null},
                {"59", null, null, null, null, null},
                {"60", null, null, null, null, null},
                {"61", null, null, null, null, null},
                {"62", null, null, null, null, null},
                {"63", null, null, null, null, null},
                {"64", null, null, null, null, null},
                {"65", null, null, null, null, null},
                {"66", null, null, null, null, null},
                {"67", null, null, null, null, null},
                {"68", null, null, null, null, null},
                {"69", null, null, null, null, null},
                {"70", null, null, null, null, null},
                {"71", null, null, null, null, null},
                {"72", null, null, null, null, null},
                {"73", null, null, null, null, null},
                {"74", null, null, null, null, null},
                {"75", null, null, null, null, null},
                {"76", null, null, null, null, null},
                {"77", null, null, null, null, null},
                {"78", null, null, null, null, null},
                {"79", null, null, null, null, null},
                {"80", null, null, null, null, null},
                {"81", null, null, null, null, null},
                {"82", null, null, null, null, null},
                {"83", null, null, null, null, null},
                {"84", null, null, null, null, null}
            },
            new String [] {
                "COUNT", "CLASS NAME", "NDI", "NIDI", "TOTAL", "CI"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Change weights");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (weight == null) {
            jDesktopPane1.removeAll();
            InheritanceWeight tbl = new InheritanceWeight();
            jDesktopPane1.add(tbl).setVisible(true);
            this.setVisible(false);
        } else {
            jDesktopPane1.removeAll();
            jDesktopPane1.add(weight).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    InheritanceWeight weight;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
