/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

//import static Coupling.CouplingMethods.coupling;
//import Coupling.CouplingTbl;
import Coupling.coupling;
import Inheritance.InheriteShow_Page;
import ctrlStricture.CtrlMethods;
import ctrlStricture.CtrlTbl;
import static home.AnalyseMethods.totalComplexity;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.net.URI;
import java.util.StringTokenizer;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import size_Method_variable.AllMethods;
import static size_Method_variable.AllMethods.methods;
import static size_Method_variable.AllMethods.variables;
import size_Method_variable.MethodTable;
import size_Method_variable.SizeTable;
import size_Method_variable.Variables;

/**
 *
 * @author PereraSupun
 */
public class CM_ToolHOME extends javax.swing.JFrame {

    Analyse analyse;

    /**
     * Creates new form NewJFrametest1
     */
    public CM_ToolHOME() {
        initComponents();

        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Abouthus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        tipFor_lbl = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btn_size = new javax.swing.JButton();
        btn_variable = new javax.swing.JButton();
        btn_method = new javax.swing.JButton();
        btn_coupling = new javax.swing.JButton();
        btn_inherit = new javax.swing.JButton();
        btn_ctrl = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        upload_btn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        analyise_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        path_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        Abouthus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/About us.png"))); // NOI18N
        Abouthus.setText("About Us");
        Abouthus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AbouthusMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/git.png"))); // NOI18N
        jLabel2.setText("GitHub");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home (3).png"))); // NOI18N
        jLabel3.setText("Home");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Abouthus)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Abouthus)
                .addComponent(jLabel2)
                .addComponent(jLabel3))
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/app-development.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "Tip For Applictaion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 1, 18))); // NOI18N

        tipFor_lbl.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        tipFor_lbl.setForeground(new java.awt.Color(0, 153, 51));
        tipFor_lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipFor_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipFor_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        btn_size.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btn_size.setText("SIZE");
        btn_size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sizeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 102;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 14, 0, 12);
        jPanel6.add(btn_size, gridBagConstraints);

        btn_variable.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btn_variable.setText("VARIABLE");
        btn_variable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_variableActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 58;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 14, 0, 12);
        jPanel6.add(btn_variable, gridBagConstraints);

        btn_method.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btn_method.setText("METHOD");
        btn_method.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_methodActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 14, 0, 12);
        jPanel6.add(btn_method, gridBagConstraints);

        btn_coupling.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btn_coupling.setText("COUPLING");
        btn_coupling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_couplingActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 14, 0, 12);
        jPanel6.add(btn_coupling, gridBagConstraints);

        btn_inherit.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btn_inherit.setText("INHERITANCE");
        btn_inherit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inheritActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 14, 0, 12);
        jPanel6.add(btn_inherit, gridBagConstraints);

        btn_ctrl.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btn_ctrl.setText("Ctrl STRUCTURE");
        btn_ctrl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ctrl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_ctrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ctrlActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 14, 19, 12);
        jPanel6.add(btn_ctrl, gridBagConstraints);

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        upload_btn.setBackground(new java.awt.Color(51, 153, 255));
        upload_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        upload_btn.setText("UPLOAD A FILE");
        upload_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_btnActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Java", "C++" }));

        analyise_btn.setBackground(new java.awt.Color(0, 204, 0));
        analyise_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        analyise_btn.setText("ANALYSE");
        analyise_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyise_btnActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel5.setText("Try you code here");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(upload_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, 107, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(analyise_btn))
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(analyise_btn))
                    .addComponent(upload_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel6.setText("Result");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Path");

        path_lbl.setForeground(new java.awt.Color(255, 0, 51));
        path_lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(path_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jDesktopPane1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(path_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AbouthusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbouthusMouseClicked
        if (a == null) {

            about_us s1 = new about_us();
            s1.setVisible(true);
        } else {
            a.removeAll();
            a.setVisible(true);
        }
    }//GEN-LAST:event_AbouthusMouseClicked

    private void upload_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_btnActionPerformed
        // Get the file to check
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        path_lbl.setText(filename);

        try {
            FileReader reader = new FileReader(filename);
            BufferedReader br = new BufferedReader(reader);
            jTextArea1.read(br, null);
            br.close();
            jTextArea1.requestFocus();
        } catch (Exception e) {
            System.out.println(e);
        }

        // Upload zip files
        try {
            FileInputStream fis = new FileInputStream(filename);
            ZipInputStream zis = new ZipInputStream(fis);
            ZipEntry ze;

            while ((ze = zis.getNextEntry()) != null) {
                jComboBox2.addItem(ze.getName());
                jTextArea1.setText("");
                zis.closeEntry();
            }

            zis.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_upload_btnActionPerformed

    private void analyise_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyise_btnActionPerformed
        String fullcode = jTextArea1.getText();

        if (fullcode.isEmpty()) {     //check weather jtext area empty or not
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "You should import a Text File for the text area !");
            if (analyse == null) {
                jDesktopPane1.removeAll();
                Analyse tbl = new Analyse();
                jDesktopPane1.add(tbl).setVisible(true);
            } else {
                jDesktopPane1.removeAll();
                jDesktopPane1.add(analyse).setVisible(true);
            }
            totalComplexity();
        }
    }//GEN-LAST:event_analyise_btnActionPerformed

    private void btn_inheritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inheritActionPerformed
         String fullcode = jTextArea1.getText();
        //get Combobox selected item value to the variable
        String combo = jComboBox1.getSelectedItem().toString();
        int total = 1;
        int finaltotal = 0;

        //chack wather jtext area empty or not
        if (fullcode.isEmpty()) {
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "You should import a Text File for the text area !");
        } else {

            //displaying the table inside the jDesktop pane
            if (in == null) {
                jDesktopPane1.removeAll();
                InheriteShow_Page i = new InheriteShow_Page();
                jDesktopPane1.add(i).setVisible(true);
            } else {
                jDesktopPane1.removeAll();
                jDesktopPane1.add(in).setVisible(true);

            }

            //Chack using the combo box
            if (combo.equals("C++")) {

                //Complexity due to Inheritance of a C++ code
                Pattern p1 = Pattern.compile(" : public");
                Matcher m1 = p1.matcher(fullcode);

                Pattern p8 = Pattern.compile(" : protected");
                Matcher m8 = p8.matcher(fullcode);

                Pattern p9 = Pattern.compile(" : private");
                Matcher m9 = p9.matcher(fullcode);

                Pattern p10 = Pattern.compile(" : abstract");
                Matcher m10 = p10.matcher(fullcode);

                Pattern p11 = Pattern.compile(" : static");
                Matcher m11 = p11.matcher(fullcode);

                Pattern p12 = Pattern.compile(" : final");
                Matcher m12 = p12.matcher(fullcode);

                Pattern p13 = Pattern.compile(" : synchronized");
                Matcher m13 = p13.matcher(fullcode);

                Pattern p14 = Pattern.compile(" : volatile");
                Matcher m14 = p14.matcher(fullcode);

                //C++ child found
                while (m1.find() || m8.find() || m9.find() || m10.find() || m11.find() || m12.find() || m13.find() || m14.find()) {

                    total = total + 1;
                    finaltotal = total - 1;
                }
                System.out.println("C++ complexity due to Inheritance : " + finaltotal);

                table();  //table methode for c++

            } else if (combo.equals("Java")) {  //Complexity due to Inheritance of a Java code

                Pattern p2 = Pattern.compile(" extends ");
                Matcher m2 = p2.matcher(fullcode);

                //Java child found
                while (m2.find()) {

                    total = total + 1;
                    finaltotal = total - 1;

                }

                System.out.println("java complexity due to inheritance : " + finaltotal);

                table();  //Table method for Displying table

            } else {
                System.out.println(jComboBox1.getSelectedItem().toString() + "Cheack your upload cord is wirte or wrong");
            }

            //Displying the tip 
            tipFor_lbl.setText("Total inheritances (Ti) = No of direct inheritances (Ndi) + No of indirect inheritances (Nidi)");

            //displying total inherite clculation in jlable
            InheriteShow_Page.total_inherit.setText(" " + finaltotal);

        }
    }//GEN-LAST:event_btn_inheritActionPerformed

    //Displying textarea values into jtable
    public void table() {

        int count = 1; // number of conditions in single line
        int finaltotal = 0;

        // Weights for each control 
        int noInherite = 0;
        int directinherie = 1;
        int inDerectInherite = 1;

        //calculate cN
        int valNothing = noInherite * count;
        int valDInherite = directinherie * count;
        int valINdirectIN = inDerectInherite * count;

        int finaltot = valDInherite + valINdirectIN;

        //convert to string
        String nC = String.valueOf(finaltot);
//        String ndi = String.valueOf(directinherie);
//        String nidi = String.valueOf(inDerectInherite);

        //convert calculated values
        String valNo = String.valueOf(valNothing);
        String valDin = String.valueOf(valDInherite);
        String valInD = String.valueOf(valINdirectIN);
        String valtot = String.valueOf(finaltot);

        String filepath = path_lbl.getText(); //get file path
        File file = new File(filepath); //create new object for file

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            //Create table heading for column
            String[] colNames = {"Count", "ClassName", "NDI", "NIDI", "Total", "CN"};

            DefaultTableModel model = (DefaultTableModel) InheriteShow_Page.jTable1.getModel();
            model.setColumnIdentifiers(colNames);

            Object[] lines = br.lines().toArray();

            // read and find the inherite classes from file line by line and check for the Inheritance
            for (int i = 1; i <= lines.length; i++) {

                String line = lines[i].toString(); //for code print
                String col = String.valueOf(i); // for number count

                String[] crinline = line.split("");
                StringTokenizer token = new StringTokenizer(line);

                while (token.hasMoreTokens()) {
                    String word = token.nextToken();

                    if (word.equals("class") || word.equals("Class")) {

                        //to find and set regex value-inherited class(table value)
                        String[] data = {col, line, valDin, valInD, valtot, nC};
                        model.addRow(data);
                    }

                }

                // Set column sizes
                InheriteShow_Page.jTable1.setAutoResizeMode(InheriteShow_Page.jTable1.AUTO_RESIZE_NEXT_COLUMN);
                TableColumnModel colModel = InheriteShow_Page.jTable1.getColumnModel();
                colModel.getColumn(0).setPreferredWidth(25);
                colModel.getColumn(1).setPreferredWidth(400);
                colModel.getColumn(2).setPreferredWidth(35);
                colModel.getColumn(3).setPreferredWidth(25);
                colModel.getColumn(4).setPreferredWidth(50);
                colModel.getColumn(5).setPreferredWidth(25);
            }

        } catch (Exception e) {

        }

    }
    
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        Desktop browser = Desktop.getDesktop();      //link with git hub page
        try {
            browser.browse(new URI("https://github.com/y3s1-2020/ITPM_2020_JAN.git"));
        } catch (Exception err) {
            System.out.println(err);
        }

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        jTextArea1.setText(null);  //refreshing with home button
        jDesktopPane1.removeAll();
        JOptionPane.showMessageDialog(null, "Code Area refreshed");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btn_sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sizeActionPerformed

        String fullcode = jTextArea1.getText();

        if (fullcode.isEmpty()) {     //chack wather jtext area empty or not
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "You should import a Text File for the text area !");
        } else {
            if (in == null) {           //creating the table inside the jDesktoppane
                jDesktopPane1.removeAll();
                SizeTable st = new SizeTable();
                jDesktopPane1.add(st).setVisible(true);
            } else {
                jDesktopPane1.removeAll();
                jDesktopPane1.add(in).setVisible(true);
            }

            AllMethods.sizeMethod();

            // show the calculation
            tipFor_lbl.setText("Cs = (Wkw * Nkw) + (Wid * Nid) + (Wop * Nop) + (Wnv * Nnv) + (Wsl * Nsl)");
        }
    }//GEN-LAST:event_btn_sizeActionPerformed

    private void btn_couplingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_couplingActionPerformed
        String fullcode = jTextArea1.getText();
        if (fullcode.isEmpty()) {
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "You should import a Text File for the text area !");
        } else {

            Coupling.coupling c1 = new coupling();
            c1.setVisible(true);

            tipFor_lbl.setText("Ccp = (Wr * Nr) + (Wmcms * Nmcms) + (Wmcmd * Nmcmd) + (Wmcrms * Nmcrms) + (Wmcrmd * Nmcrmd) + (Wrmcrms * Nrmcrms) + (Wrmcrmd *Nrmcrmd) + (Wrmcms * Nrmcms) + (Wrmcmd * Nrmcmd) + (Wmrgvs *Nmrgvs) + (Wmrgvd * Nmrgvd) + (Wrmrgvs * Nrmrgvs) + (Wrmrgvd * Nrmrgvd)");
        }
    }//GEN-LAST:event_btn_couplingActionPerformed

    private void btn_ctrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ctrlActionPerformed

        String fullcode = jTextArea1.getText();
        if (fullcode.isEmpty()) {
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "You should import a Text File for the text area !");
        } else {

            if (ctrl == null) {
                jDesktopPane1.removeAll();
                CtrlTbl tbl = new CtrlTbl();
                jDesktopPane1.add(tbl).setVisible(true);
            } else {
                jDesktopPane1.removeAll();
                jDesktopPane1.add(ctrl).setVisible(true);
            }
            CtrlMethods.ctrlStructures();

            // Show the calculation
            tipFor_lbl.setText("Ccs = (Wtcs * NC) + Ccspps");
        }
    }//GEN-LAST:event_btn_ctrlActionPerformed

    private void btn_variableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_variableActionPerformed

        String fullcode = jTextArea1.getText();
        if (fullcode.isEmpty()) {
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "You should import a Text File for the text area !");
        } else {

            if (ctrl == null) {
                jDesktopPane1.removeAll();
                Variables tbl = new Variables();
                jDesktopPane1.add(tbl).setVisible(true);
            } else {
                jDesktopPane1.removeAll();
                jDesktopPane1.add(var).setVisible(true);
            }
            variables();

            tipFor_lbl.setText("Cv = Wvs [(Wpdtv * Npdtv) + (Wcdtv * Ncdtv)]");
        }
    }//GEN-LAST:event_btn_variableActionPerformed

    private void btn_methodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_methodActionPerformed

        String fullcode = jTextArea1.getText();

        if (fullcode.isEmpty()) {     //chack wather jtext area empty or not
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "You should import a Text File for the text area !");
        } else {
            if (in == null) {           //creating the table inside the jDesktoppane

                jDesktopPane1.removeAll();
                MethodTable mr = new MethodTable();
                jDesktopPane1.add(mr).setVisible(true);
            } else {
                jDesktopPane1.removeAll();
                jDesktopPane1.add(in).setVisible(true);

            }

            methods();

            tipFor_lbl.setText("Cm = Wmrt + (Wpdtp * Npdtp) + (Wcdtp * Ncdtp)");
        }
    }//GEN-LAST:event_btn_methodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CM_ToolHOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CM_ToolHOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CM_ToolHOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CM_ToolHOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CM_ToolHOME().setVisible(true);
            }
        });
    }

    InheriteShow_Page in;
    about_us a;
    Variables var;

    CtrlTbl ctrl;
    coupling cop;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Abouthus;
    private javax.swing.JButton analyise_btn;
    private javax.swing.JButton btn_coupling;
    private javax.swing.JButton btn_ctrl;
    private javax.swing.JButton btn_inherit;
    private javax.swing.JButton btn_method;
    private javax.swing.JButton btn_size;
    private javax.swing.JButton btn_variable;
    public static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static final javax.swing.JTextArea jTextArea1 = new javax.swing.JTextArea();
    public static javax.swing.JLabel path_lbl;
    private javax.swing.JLabel tipFor_lbl;
    private javax.swing.JButton upload_btn;
    // End of variables declaration//GEN-END:variables

}
